version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: qkbn
    main: ./cmd/qkbn
    binary: qkbn
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/jtprogru/qkbn/cmd.Version={{.Version}} -X github.com/jtprogru/qkbn/cmd.Commit={{.Commit}} -X github.com/jtprogru/qkbn/cmd.Date={{.CommitDate}}

archives:
  - formats: ["tar.gz"]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        formats: ["zip"]
    files:
      - README.md

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
